package com.ccnu.utils;

/**
 * @program: ccnu-bd
 * @description: 数据表格枚举
 * @author: lsc
 * @create: 2021-11-02 17:05
 **/
public enum DataSheetInfoEnum {
    //注意：这里每个json中key对应的是数据库中的字段名，value对应的是excel中的列名。导师唯一识别码、博士生唯一识别码、合作指导导师唯一识别码、获奖博士生唯一标识码字段例外，
    // 因为导出的标识码数据需要加上固定编码，所以sql有一定的处理，需要用其他字段代替。

    FORM_1_1_1_merge("表1-1-1 博士导师信息", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"name\":\"姓名\",\n"
            + "    \"college\":\"所属学院(单位)\",\n"
            + "    \"country\":\"国家(地区)\",\n"
            + "    \"type_of_certificate\":\"证件类型\",\n"
            + "    \"certificate_number\":\"证件号码\",\n"
            + "    \"birthday\":\"出生日期\",\n"
            + "    \"sex\":\"性别\",\n"
            + "    \"age\":\"年龄\",\n"
            + "    \"nationality\":\"民族\",\n"
            + "    \"political_status\":\"政治面貌\",\n"
            + "    \"highest_education\":\"最高学历\",\n"
            + "    \"obtain_highest_education_country\":\"获得最高学历的国家(地区)\",\n"
            + "    \"institution_with_highest_degree\":\"获得最高学历的院校或机构\",\n"
            + "    \"major_highest_degree\":\"获最高学历所学专业\",\n"
            + "    \"highest_degree_level\":\"最高学位层次\",\n"
            + "    \"name_by_highest_degree\":\"最高学位名称\",\n"
            + "    \"country_with_the_highest_degree\":\"获最高学位的国家(地区)\",\n"
            + "    \"highest_degree_institution\":\"获最高学位的院校或机构\",\n"
            + "    \"participation_date\":\"参加工作日期\",\n"
            + "    \"first_date_of_admission_to_doctoral_students\":\"首次具有博士生招生资格日期\",\n"
            + "    \"in_the_staff\":\"是否在编\",\n"
            + "    \"sign_contract_with_institution\":\"是否与填报单位签订聘用合同\",\n"
            + "    \"employment_period\":\"聘用期限\",\n"
            + "    \"full_time_job_in_unit\":\"是否于填报单位承担全职工作\",\n"
            + "    \"full_time_job_unit\":\"全职工作单位\",\n"
            + "    \"is_retire\":\"是否为离退休人员\",\n"
            + "    \"professional_and_technical_positions\":\"聘任专业技术职务\",\n"
            + "    \"post_rating\":\"岗位等级\",\n"
            + "    \"party_and_government_duties\":\"党政职务\",\n"
            + "    \"overseas_training_experience\":\"海外研修（访学）经历\",\n"
            + "    \"name_of_selected_talent_project_and_year_of_selection\":\"入选人才项目名称及入选年份\",\n"
            + "    \"have_other_industry_technical_titles\":\"是否具有其他行业技术职称\",\n"
            + "    \"have_academic_part_time_at_home_and_abroad\":\"是否具有国内外学术兼职\",\n"
            + "    \"tutor_category\":\"导师类别\",\n"
            + "    \"have_international_cooperation\":\"是否有国际合作\",\n"
            + "    \"guide_doctoral_students\":\"可指导博士生类型\",\n"
            + "    \"first_level_subject\":\"现所属一级学科\",\n"
            + "    \"second_level_subject\":\"现所属二级学科\",\n"
            + "    \"guide_professional_degree_types\":\"可指导专业学位类型\",\n"
            + "    \"number_of_master_students_enrolled_in_the_unit\":\"所指导填报单位硕士生在读人数（人）\"\n"
            + "}"),
    FROM_1_1_1("表1-1-1 博士导师信息", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"name\":\"姓名\",\n"
            + "    \"college\":\"所属学院(单位)\",\n"
            + "    \"country\":\"国家(地区)\",\n"
            + "    \"type_of_certificate\":\"证件类型\",\n"
            + "    \"certificate_number\":\"证件号码\",\n"
            + "    \"birthday\":\"出生日期\",\n"
            + "    \"sex\":\"性别\",\n"
            + "    \"age\":\"年龄\",\n"
            + "    \"nationality\":\"民族\",\n"
            + "    \"political_status\":\"政治面貌\",\n"
            + "    \"highest_education\":\"最高学历\",\n"
            + "    \"obtain_highest_education_country\":\"获得最高学历的国家(地区)\",\n"
            + "    \"institution_with_highest_degree\":\"获得最高学历的院校或机构\",\n"
            + "    \"major_highest_degree\":\"获最高学历所学专业\",\n"
            + "    \"highest_degree_level\":\"最高学位层次\",\n"
            + "    \"name_by_highest_degree\":\"最高学位名称\",\n"
            + "    \"country_with_the_highest_degree\":\"获最高学位的国家(地区)\",\n"
            + "    \"highest_degree_institution\":\"获最高学位的院校或机构\"\n"
            + "}"),
    FROM_1_1_1_xu1("表1-1-1博士导师信息（续1）", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"participation_date\":\"参加工作日期\",\n"
            + "    \"first_date_of_admission_to_doctoral_students\":\"首次具有博士生招生资格日期\",\n"
            + "    \"in_the_staff\":\"是否在编\",\n"
            + "    \"sign_contract_with_institution\":\"是否与填报单位签订聘用合同\",\n"
            + "    \"employment_period\":\"聘用期限\",\n"
            + "    \"full_time_job_in_unit\":\"是否于填报单位承担全职工作\",\n"
            + "    \"full_time_job_unit\":\"全职工作单位\",\n"
            + "    \"is_retire\":\"是否为离退休人员\",\n"
            + "    \"professional_and_technical_positions\":\"聘任专业技术职务\",\n"
            + "    \"post_rating\":\"岗位等级\",\n"
            + "    \"party_and_government_duties\":\"党政职务\",\n"
            + "    \"overseas_training_experience\":\"海外研修（访学）经历\",\n"
            + "    \"name_of_selected_talent_project_and_year_of_selection\":\"入选人才项目名称及入选年份\",\n"
            + "    \"have_other_industry_technical_titles\":\"是否具有其他行业技术职称\",\n"
            + "    \"have_academic_part_time_at_home_and_abroad\":\"是否具有国内外学术兼职\"\n"
            + "}"),
    FROM_1_1_1_xu2("表1-1-1 博士导师信息表（续2）", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"tutor_category\":\"导师类别\",\n"
            + "    \"have_international_cooperation\":\"是否有国际合作\",\n"
            + "    \"guide_doctoral_students\":\"可指导博士生类型\",\n"
            + "    \"first_level_subject\":\"现所属一级学科\",\n"
            + "    \"second_level_subject\":\"现所属二级学科\",\n"
            + "    \"guide_professional_degree_types\":\"可指导专业学位类型\",\n"
            + "    \"number_of_master_students_enrolled_in_the_unit\":\"所指导填报单位硕士生在读人数（人）\"\n"
            + "}"),
    FROM_1_1_2("表1-1-2 博士生信息表", "{\n"
            + "    \"student_id\":\"博士生唯一识别码\",\n"
            + "    \"name\":\"姓名\",\n"
            + "    \"tutor_id\":\"博士导师唯一识别码\",\n"
            + "    \"tutor_name\":\"博士导师姓名\",\n"
            + "    \"cooperative_tutor_id\":\"合作指导导师唯一识别码\",\n"
            + "    \"student_type\":\"学生类型\",\n"
            + "    \"way_of_learning\":\"学习方式\",\n"
            + "    \"country\":\"国家（地区）\",\n"
            + "    \"nationality\":\"民族\",\n"
            + "    \"degree_type\":\"学位类型\",\n"
            + "    \"first_level_subject\":\"现所属一级学科\",\n"
            + "    \"second_level_subject\":\"现所属二级学科\",\n"
            + "    \"current_professional_degree_category\":\"现所属专业学位类别\",\n"
            + "    \"entry_date\":\"入学日期\",\n"
            + "    \"have_change_in_student_status\":\"是否存在学籍变动\",\n"
            + "    \"reasons_for_changes_in_student_status\":\"学籍变动原因\",\n"
            + "    \"whether_to_award_degree\":\"是否授予学位\"\n"
            + "}"),
    FROM_1_2_1("表1-2-1 科研项目情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"project_name\":\"项目名称\",\n"
            + "    \"project_date\":\"立项日期\",\n"
            + "    \"project_number\":\"立项编号\",\n"
            + "    \"project_type\":\"项目类型\",\n"
            + "    \"vertical_project_type\":\"纵向项目类别\",\n"
            + "    \"project_status\":\"项目状态\",\n"
            + "    \"domestic_project_contract_amount\":\"国内项目合同金额（万元）\",\n"
            + "    \"abroad_project_contract_amount\":\"国际项目合同金额（万元）\",\n"
            + "    \"accumulated_items\":\"项目累积到款（万元）\",\n"
            + "    \"project_year_to_payment\":\"项目年度到款（万元）\",\n"
            + "    \"final_acceptance_or_identification_time\":\"结题验收或鉴定时间\",\n"
            + "    \"role\":\"角色\"\n"
            + "}"),
    FROM_2_1_1("表2-1-1 开课情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"course_number\":\"课程编号\",\n"
            + "    \"course_name\":\"课程名称\",\n"
            + "    \"course_type\":\"课程类别\",\n"
            + "    \"course_nature\":\"课程性质\",\n"
            + "    \"teaching_hours\":\"教学学时\",\n"
            + "    \"course_object\":\"开课对象\",\n"
            + "    \"number_of_students\":\"上课人数(人)\"\n"
            + "}"),
    FROM_2_1_2("表2-1-2 研究生教育教学改革研究项目情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"project_name\":\"项目名称\",\n"
            + "    \"project_date\":\"立项日期\",\n"
            + "    \"project_status\":\"项目状态\",\n"
            + "    \"end_of_date\":\"结束日期\",\n"
            + "    \"project_level\":\"项目等级\",\n"
            + "    \"project_funding\":\"立项经费(万元)\",\n"
            + "    \"sources_of_funding\":\"经费来源\",\n"
            + "    \"role\":\"本人角色\"\n"
            + "}"),
    FROM_2_1_3("表2-1-3 出版教材情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"textbook_name\":\"教材名称\",\n"
            + "    \"situation_with_selected_textbooks\":\"教材入选情况\",\n"
            + "    \"publishing_house\":\"出版社\",\n"
            + "    \"publisher_country\":\"出版社所在国家（地区）\",\n"
            + "    \"total_number_of_words\":\"总字数(万字)\",\n"
            + "    \"number_of_issues\":\"发行数(册)\",\n"
            + "    \"publication_date\":\"出版日期\",\n"
            + "    \"book_number\":\"书号（ISBN）\",\n"
            + "    \"publishing_language\":\"出版语言\",\n"
            + "    \"role\":\"本人角色\"\n"
            + "}"),
    FROM_2_1_4("表2-1-4 研究生教学成果获奖情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"completion_order\":\"完成人序位\",\n"
            + "    \"award_name\":\"奖项名称\",\n"
            + "    \"certificate_number\":\"证书号\",\n"
            + "    \"whether_first_winning_unit_is_filling_unit\":\"第一获奖单位是否为填表单位\",\n"
            + "    \"award_level\":\"获奖级别\",\n"
            + "    \"award_grade\":\"获奖等级\",\n"
            + "    \"award_date\":\"获奖日期\",\n"
            + "    \"awarding_unit\":\"颁奖单位\"\n"
            + "}"),
    FROM_2_1_5("表2-1-5 指导博士生获奖情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"award_topic\":\"获奖题目\",\n"
            + "    \"award_name\":\"奖项名称\",\n"
            + "    \"certificate_number\":\"证书号\",\n"
            + "    \"award_level\":\"获奖级别\",\n"
            + "    \"award_grade\":\"获奖等级\",\n"
            + "    \"awarding_unit\":\"颁奖单位\",\n"
            + "    \"award_student_id\":\"获奖博士生唯一识别码\",\n"
            + "    \"instructor_order\":\"指导教师序位\"\n"
            + "}"),
    FROM_2_2_1("表2-2-1 科研论文情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"paper_name\":\"论文名称\",\n"
            + "    \"paper_type\":\"论文类型\",\n"
            + "    \"journal_name\":\"期刊名称\",\n"
            + "    \"issue_number\":\"期刊号（ISSN）\",\n"
            + "    \"publishing_language\":\"发表语言\",\n"
            + "    \"DOI\":\"DOI\",\n"
            + "    \"whether_esi_is_included\":\"是否ESI收录\",\n"
            + "    \"index\":\"收录索引\",\n"
            + "    \"author_order\":\"作者序位\",\n"
            + "    \"whether_corresponding_author\":\"是否通讯作者\"\n"
            + "}"),
    FROM_2_2_2("表2-2-2 科研获奖情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"award_level\":\"获奖级别\",\n"
            + "    \"award_name\":\"奖项名称\",\n"
            + "    \"whether_first_completed_unit\":\"本单位是否为第一完成单位\",\n"
            + "    \"award_category\":\"获奖类别\",\n"
            + "    \"award_grade\":\"获奖等级\",\n"
            + "    \"award_date\":\"获奖日期\",\n"
            + "    \"awarding_unit\":\"颁奖单位\",\n"
            + "    \"award_certificate_number\":\"获奖证书编号\",\n"
            + "    \"complete_unit_ranking\":\"完成单位排名\",\n"
            + "    \"sort_by_name\":\"本人排序\"\n"
            + "}"),
    FROM_2_2_3("表2-2-3 出版著作情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"book_name\":\"著作名称\",\n"
            + "    \"book_type\":\"著作类别\",\n"
            + "    \"publishing_house\":\"出版社\",\n"
            + "    \"publisher_country\":\"出版社所在国家（地区）\",\n"
            + "    \"total_number_of_words\":\"总字数（万字）\",\n"
            + "    \"number_of_issues\":\"发行数（册）\",\n"
            + "    \"publication_date\":\"出版日期\",\n"
            + "    \"book_number\":\"书号（ISBN）\",\n"
            + "    \"language\":\"语种\",\n"
            + "    \"role\":\"本人角色\"\n"
            + "}"),
    FROM_2_2_4("表2-2-4  专利（著作权）授权情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"patent_or_book_name\":\"专利（著作权）名称\",\n"
            + "    \"intellectual_property_category\":\"知识产权类别\",\n"
            + "    \"authorization_number\":\"授权号\",\n"
            + "    \"approved_date\":\"获批日期\",\n"
            + "    \"sort_by_me\":\"本人排序\",\n"
            + "    \"whether_unit_is_first_application_unit\":\"本单位是否为第一申请单位\",\n"
            + "    \"whether_industry_joint_patent\":\"是否行业联合专利（著作权）\"\n"
            + "}"),
    FROM_2_2_5("表2-2-5 参加国际学术会议情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"academic_conference_name\":\"学术会议名\",\n"
            + "    \"organizer\":\"主办单位\",\n"
            + "    \"conference_held_country_or_region\":\"会议举办所在国家/地区\",\n"
            + "    \"conference_city\":\"会议举办所在城市\",\n"
            + "    \"opening_date_of_meeting\":\"会议开幕日期\",\n"
            + "    \"whether_chairman_of_conference\":\"是否为大会主席\",\n"
            + "    \"report_type\":\"报告类型\",\n"
            + "    \"report_name\":\"报告题目\",\n"
            + "    \"report_date\":\"报告日期\",\n"
            + "    \"reporter\":\"报告人\"\n"
            + "}"),
    FROM_2_2_6("表2-2-6 学术任职情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"job_title\":\"职务名称\",\n"
            + "    \"job_level\":\"职务级别\",\n"
            + "    \"employment_organization\":\"任职组织\",\n"
            + "    \"organization_type\":\"组织类型\",\n"
            + "    \"start_of_office\":\"开始任职年月\"\n"
            + "}"),
    FROM_2_2_7("表2-2-7 依托科研平台情况", "{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"tutor_name\":\"导师姓名\",\n"
            + "    \"research_platform_name\":\"科研平台名称\",\n"
            + "    \"research_platform_level\":\"科研平台级别\",\n"
            + "    \"research_platform_category\":\"科研平台类别\",\n"
            + "    \"provincial_and_ministerial_authorities\":\"省部级主管部门\",\n"
            + "    \"serve\":\"任职\"\n"
            + "}"),
    INCOMPLETE("未采集完成的博导信息","{\n"
            + "    \"tutor_id\":\"导师唯一识别码\",\n"
            + "    \"name\":\"姓名\",\n"
            + "    \"college\":\"所属学院(单位)\"\n"
            + "}");

    private String name;
    private String columnName;

    DataSheetInfoEnum(String name, String columnName) {
        this.name = name;
        this.columnName = columnName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getColumnName() {
        return columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
}
